### ISSUE TITLE
what medium you are using for messaging?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Satellite-im/Satellite-Absolute#11]
- afaik you use solana for high trust stuff like registry
- I have seen solana anchor example which stores message on chain, but that seems not will work
- afaik you are using ipfs for files
- what is used for compute and messaging?
- as per videos from these https://fluence.network/ they took nieche above  blockhain (so they do less trust compute, but still have trustgraph to choose level of trust), and ipfs and solana are gates into services. their main example is chat app in youtube video.

**Comment by dzmitry-lahoda** [comment]
- so there is gate to ipfs https://github.com/fluencelabs/examples/tree/1946f8f544f2707c658d7c65c2c3878459d3bf89/ipfs-node 
- solana gate can be written in rust (or in ts, but rust seems better)
- to store message of less importance can do https://github.com/fluencelabs/examples/tree/1946f8f544f2707c658d7c65c2c3878459d3bf89/sqlite or they have wrapper for redis (wasm compiled?) . so small message can be solved. may be each dweller to have its own copy? and can restore copy from  other dweller and devices?
- somehow merge solana with https://github.com/fluencelabs/trust-graph so credentials flow back and forth transparently

**Comment by dzmitry-lahoda** [comment]
fluence generates ts code for p2p node to node client to service flows (so devices are just flow started), easy to describe and read. so satellite will be 1. client code to start flows (combination of p2p call jumps) 2. credentials provider/storage

**Comment by RetroPronghorn** [comment]
Right now the plan is to use https://textile.io/ specifically their MailBox API for direct messages, and some form of threads for interactions on larger scale like servers & communities (You can see this in the legacy Satellite repo). We will likely have alternative options available as we want the product to be flexible.
