### ISSUE TITLE
Friendly name gets lost

### ISSUE THREAD

**Issue by WanderingHogan** [Satellite-im/Satellite-Absolute#4648]
![Screen Shot 2022-09-07 at 10 01 33 AM](https://user-images.githubusercontent.com/2993032/188925772-976e3984-6004-4c10-a040-057d95af45b2.png)
![Screen Shot 2022-09-07 at 10 01 36 AM](https://user-images.githubusercontent.com/2993032/188925784-8bc45594-cfb8-4437-96cb-8de98fe93159.png)
![Screen Shot 2022-09-07 at 10 01 27 AM](https://user-images.githubusercontent.com/2993032/188925789-2219174f-a9cd-418b-87ca-a41dd04ca061.png)
![Screen Shot 2022-09-07 at 10 01 21 AM](https://user-images.githubusercontent.com/2993032/188925793-34f8acc6-e1eb-4b7e-aabb-56cdefc6452b.png)

Friendly name gets lost client side sometimes - Sheldon was not having this issue on his side

**Comment by WanderingHogan** [comment]
It looks like the user object in iridium has the did for the id and for the name

**Comment by WanderingHogan** [comment]
I was starting to debug here: `libraries/Iridium/users/UsersManager.ts` - the id and name are both the user did, and like joe mentioned it could be in the iridium repo

This mostly happens after a reload or a couple of reloads - and is inconsistent, but when i see it happen, it doesn't usually correct itself

**Comment by aewing** [comment]
This should definitely be fixed now
